baseURL = "https://shmel.xyz/"
languageCode = "en-us"
title = "5HM3L TEAM BLOG"
theme = "cactus"
copyright = "by 5HM3L team" # cactus will use title if copyright is not set
disqusShortname = "5HM3L" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About Team"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "light"
    tabWidth = 4

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "Official blog of the CTF 5HM3L team community"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/5HM3L" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "https://cactus.chat/" # see https://cactus.chat/ on how to register your site name
      serverUrl = "https://matrix.cactus.chat:8448" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      serverName = "cactus.chat" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
    name = "telegram"
    link = "https://t.me/shmelovod"
[[params.social]]
    name = "email"
    link = "5hm3l1337@gmail.com"
[[params.social]]
    name = "github"
    link = "https://github.com/5HM3L"